# Deployment do Mongo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_INITDB_ROOT_USERNAME
              value: "mongouser"
            - name: MONGODB_INITDB_ROOT_PASSWORD
              value: "mongopwd"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotten-potatoes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rotten-potatoes
  template:
    metadata:
      labels:
        app: rotten-potatoes
    spec:
      containers:
        - name: rotten-potatoes
          image: matrixsoft1/rotten-potatoes:v1
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_DB
              value: "admin"
            - name: MONGODB_HOST
              value: "mongodb-service"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: "mongouser"
            - name: MONGODB_PASSWORD
              value: "mongopwd"
---
apiVersion: v1
kind: Service
metadata:
  name: rotten-potatoes-service
spec:
  selector:
    app: rotten-potatoes
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: LoadBalancer
